---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  labels:
    role: backend
    infras: s8
spec:
  ports:
  - name: transport
    port: 9300
  selector:
    app: elasticsearch
    role: elasticsearch-master
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-client
  labels:
    role: backend
    infra: s8
spec:
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  selector:
    app: elasticsearch
    role: elasticsearch-client
